export const cities = [
  {
    "city": "", 
    "lat": "", 
    "lng": "", 
    "country": "", 
    "iso2": "", 
    "admin_name": "", 
    "capital": "", 
    "population": "", 
    "population_proper": ""
  }, 
    {
      "city": "Bucharest", 
      "lat": "44.4000", 
      "lng": "26.0833", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bucureşti", 
      "capital": "primary", 
      "population": "1883425", 
      "population_proper": "1883425"
    }, 
    {
      "city": "Timişoara", 
      "lat": "45.7597", 
      "lng": "21.2300", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Timiş", 
      "capital": "admin", 
      "population": "319279", 
      "population_proper": "319279"
    }, 
    {
      "city": "Cluj", 
      "lat": "46.7667", 
      "lng": "23.6000", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Cluj", 
      "capital": "admin", 
      "population": "316748", 
      "population_proper": "282141"
    }, 
    {
      "city": "Braşov", 
      "lat": "45.6500", 
      "lng": "25.6000", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Braşov", 
      "capital": "admin", 
      "population": "290743", 
      "population_proper": "290743"
    }, 
    {
      "city": "Iaşi", 
      "lat": "47.1622", 
      "lng": "27.5889", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Iaşi", 
      "capital": "admin", 
      "population": "290422", 
      "population_proper": "290422"
    }, 
    {
      "city": "Constanţa", 
      "lat": "44.1733", 
      "lng": "28.6383", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Constanţa", 
      "capital": "admin", 
      "population": "283872", 
      "population_proper": "283872"
    }, 
    {
      "city": "Craiova", 
      "lat": "44.3333", 
      "lng": "23.8167", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Dolj", 
      "capital": "admin", 
      "population": "269506", 
      "population_proper": "269506"
    }, 
    {
      "city": "Galaţi", 
      "lat": "45.4233", 
      "lng": "28.0425", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Galaţi", 
      "capital": "admin", 
      "population": "249432", 
      "population_proper": "249432"
    }, 
    {
      "city": "Ploieşti", 
      "lat": "44.9386", 
      "lng": "26.0225", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Prahova", 
      "capital": "admin", 
      "population": "209945", 
      "population_proper": "209945"
    }, 
    {
      "city": "Oradea", 
      "lat": "47.0722", 
      "lng": "21.9211", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bihor", 
      "capital": "admin", 
      "population": "196367", 
      "population_proper": "196367"
    }, 
    {
      "city": "Brăila", 
      "lat": "45.2692", 
      "lng": "27.9575", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Brăila", 
      "capital": "admin", 
      "population": "180302", 
      "population_proper": "180302"
    }, 
    {
      "city": "Arad", 
      "lat": "46.1667", 
      "lng": "21.3167", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Arad", 
      "capital": "admin", 
      "population": "159074", 
      "population_proper": "159074"
    }, 
    {
      "city": "Piteşti", 
      "lat": "44.8667", 
      "lng": "24.8833", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Argeş", 
      "capital": "admin", 
      "population": "155383", 
      "population_proper": "155383"
    }, 
    {
      "city": "Sibiu", 
      "lat": "45.8000", 
      "lng": "24.1500", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Sibiu", 
      "capital": "admin", 
      "population": "147245", 
      "population_proper": "147245"
    }, 
    {
      "city": "Bacău", 
      "lat": "46.5833", 
      "lng": "26.9167", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bacău", 
      "capital": "admin", 
      "population": "144307", 
      "population_proper": "144307"
    }, 
    {
      "city": "Târgu-Mureş", 
      "lat": "46.5497", 
      "lng": "24.5597", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Mureş", 
      "capital": "admin", 
      "population": "134290", 
      "population_proper": "134290"
    }, 
    {
      "city": "Baia Mare", 
      "lat": "47.6597", 
      "lng": "23.5819", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Maramureş", 
      "capital": "admin", 
      "population": "123738", 
      "population_proper": "123738"
    }, 
    {
      "city": "Buzău", 
      "lat": "45.1517", 
      "lng": "26.8167", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Buzău", 
      "capital": "admin", 
      "population": "115494", 
      "population_proper": "115494"
    }, 
    {
      "city": "Botoşani", 
      "lat": "47.7486", 
      "lng": "26.6694", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Botoşani", 
      "capital": "admin", 
      "population": "106847", 
      "population_proper": "106847"
    }, 
    {
      "city": "Satu Mare", 
      "lat": "47.7900", 
      "lng": "22.8900", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Satu Mare", 
      "capital": "admin", 
      "population": "102411", 
      "population_proper": "102411"
    }, 
    {
      "city": "Râmnicu Vâlcea", 
      "lat": "45.1047", 
      "lng": "24.3756", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Vâlcea", 
      "capital": "admin", 
      "population": "98776", 
      "population_proper": "98776"
    }, 
    {
      "city": "Drobeta-Turnu Severin", 
      "lat": "44.6361", 
      "lng": "22.6556", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Mehedinţi", 
      "capital": "admin", 
      "population": "92617", 
      "population_proper": "92617"
    }, 
    {
      "city": "Tulcea", 
      "lat": "45.1993", 
      "lng": "28.7967", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Tulcea", 
      "capital": "admin", 
      "population": "92475", 
      "population_proper": "86288"
    }, 
    {
      "city": "Suceava", 
      "lat": "47.6514", 
      "lng": "26.2556", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Suceava", 
      "capital": "admin", 
      "population": "92121", 
      "population_proper": "92121"
    }, 
    {
      "city": "Piatra Neamţ", 
      "lat": "46.9275", 
      "lng": "26.3708", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Neamţ", 
      "capital": "admin", 
      "population": "85055", 
      "population_proper": "85055"
    }, 
    {
      "city": "Reşiţa", 
      "lat": "45.2970", 
      "lng": "21.8865", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Caraş-Severin", 
      "capital": "admin", 
      "population": "83324", 
      "population_proper": "81228"
    }, 
    {
      "city": "Târgu Jiu", 
      "lat": "45.0342", 
      "lng": "23.2747", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Gorj", 
      "capital": "admin", 
      "population": "82504", 
      "population_proper": "82504"
    }, 
    {
      "city": "Târgovişte", 
      "lat": "44.9244", 
      "lng": "25.4572", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Dâmboviţa", 
      "capital": "admin", 
      "population": "79610", 
      "population_proper": "79610"
    }, 
    {
      "city": "Focşani", 
      "lat": "45.6997", 
      "lng": "27.1797", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Vrancea", 
      "capital": "admin", 
      "population": "79315", 
      "population_proper": "79315"
    }, 
    {
      "city": "Bistriţa", 
      "lat": "47.1333", 
      "lng": "24.4833", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bistriţa-Năsăud", 
      "capital": "admin", 
      "population": "75076", 
      "population_proper": "75076"
    }, 
    {
      "city": "Slatina", 
      "lat": "44.4297", 
      "lng": "24.3642", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Olt", 
      "capital": "admin", 
      "population": "70293", 
      "population_proper": "70293"
    }, 
    {
      "city": "Călăraşi", 
      "lat": "44.2000", 
      "lng": "27.3333", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Călăraşi", 
      "capital": "admin", 
      "population": "65181", 
      "population_proper": "65181"
    }, 
    {
      "city": "Alba Iulia", 
      "lat": "46.0764", 
      "lng": "23.5728", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Alba", 
      "capital": "admin", 
      "population": "63536", 
      "population_proper": "63536"
    }, 
    {
      "city": "Giurgiu", 
      "lat": "43.9000", 
      "lng": "25.9667", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Giurgiu", 
      "capital": "admin", 
      "population": "61353", 
      "population_proper": "61353"
    }, 
    {
      "city": "Deva", 
      "lat": "45.8719", 
      "lng": "22.9117", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "", 
      "population": "61123", 
      "population_proper": "61123"
    }, 
    {
      "city": "Hunedoara", 
      "lat": "45.7697", 
      "lng": "22.9203", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "admin", 
      "population": "60525", 
      "population_proper": "60525"
    }, 
    {
      "city": "Zalău", 
      "lat": "47.1911", 
      "lng": "23.0572", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Sălaj", 
      "capital": "admin", 
      "population": "56202", 
      "population_proper": "56202"
    }, 
    {
      "city": "Sfântu-Gheorghe", 
      "lat": "45.8636", 
      "lng": "25.7875", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Covasna", 
      "capital": "admin", 
      "population": "56006", 
      "population_proper": "56006"
    }, 
    {
      "city": "Bârlad", 
      "lat": "46.2167", 
      "lng": "27.6667", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Vaslui", 
      "capital": "", 
      "population": "55837", 
      "population_proper": "55837"
    }, 
    {
      "city": "Vaslui", 
      "lat": "46.6383", 
      "lng": "27.7292", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Vaslui", 
      "capital": "admin", 
      "population": "55407", 
      "population_proper": "55407"
    }, 
    {
      "city": "Roman", 
      "lat": "46.9300", 
      "lng": "26.9300", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Neamţ", 
      "capital": "", 
      "population": "50713", 
      "population_proper": "50713"
    }, 
    {
      "city": "Turda", 
      "lat": "46.5667", 
      "lng": "23.7833", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Cluj", 
      "capital": "", 
      "population": "47744", 
      "population_proper": "47744"
    }, 
    {
      "city": "Mediaş", 
      "lat": "46.1639", 
      "lng": "24.3508", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Sibiu", 
      "capital": "", 
      "population": "47204", 
      "population_proper": "47204"
    }, 
    {
      "city": "Slobozia", 
      "lat": "44.5639", 
      "lng": "27.3661", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Ialomiţa", 
      "capital": "admin", 
      "population": "45891", 
      "population_proper": "45891"
    }, 
    {
      "city": "Alexandria", 
      "lat": "43.9686", 
      "lng": "25.3333", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Teleorman", 
      "capital": "admin", 
      "population": "45434", 
      "population_proper": "45434"
    }, 
    {
      "city": "Voluntari", 
      "lat": "44.4925", 
      "lng": "26.1914", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bucureşti", 
      "capital": "", 
      "population": "42944", 
      "population_proper": "42944"
    }, 
    {
      "city": "Miercurea-Ciuc", 
      "lat": "46.3610", 
      "lng": "25.5240", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Harghita", 
      "capital": "admin", 
      "population": "42029", 
      "population_proper": "37980"
    }, 
    {
      "city": "Lugoj", 
      "lat": "45.6861", 
      "lng": "21.9006", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Timiş", 
      "capital": "", 
      "population": "40361", 
      "population_proper": "40361"
    }, 
    {
      "city": "Medgidia", 
      "lat": "44.2503", 
      "lng": "28.2614", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Constanţa", 
      "capital": "", 
      "population": "39780", 
      "population_proper": "39780"
    }, 
    {
      "city": "Oneşti", 
      "lat": "46.2500", 
      "lng": "26.7667", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Bacău", 
      "capital": "", 
      "population": "39172", 
      "population_proper": "39172"
    }, 
    {
      "city": "Sighetu Marmaţiei", 
      "lat": "47.9309", 
      "lng": "23.8947", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Maramureş", 
      "capital": "", 
      "population": "37640", 
      "population_proper": "37640"
    }, 
    {
      "city": "Petroşani", 
      "lat": "45.4122", 
      "lng": "23.3733", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "", 
      "population": "37160", 
      "population_proper": "37160"
    }, 
    {
      "city": "Mangalia", 
      "lat": "43.8172", 
      "lng": "28.5828", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Constanţa", 
      "capital": "", 
      "population": "36364", 
      "population_proper": "36364"
    }, 
    {
      "city": "Tecuci", 
      "lat": "45.8467", 
      "lng": "27.4278", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Galaţi", 
      "capital": "", 
      "population": "34871", 
      "population_proper": "34871"
    }, 
    {
      "city": "Odorheiu Secuiesc", 
      "lat": "46.3139", 
      "lng": "25.3017", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Harghita", 
      "capital": "", 
      "population": "34257", 
      "population_proper": "34257"
    }, 
    {
      "city": "Râmnicu Sărat", 
      "lat": "45.3800", 
      "lng": "27.0600", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Buzău", 
      "capital": "", 
      "population": "33843", 
      "population_proper": "33843"
    }, 
    {
      "city": "Paşcani", 
      "lat": "47.2519", 
      "lng": "26.7231", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Iaşi", 
      "capital": "", 
      "population": "33745", 
      "population_proper": "33745"
    }, 
    {
      "city": "Dej", 
      "lat": "47.0872", 
      "lng": "23.8053", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Cluj", 
      "capital": "", 
      "population": "33497", 
      "population_proper": "33497"
    }, 
    {
      "city": "Reghin", 
      "lat": "46.7758", 
      "lng": "24.7083", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Mureş", 
      "capital": "", 
      "population": "33281", 
      "population_proper": "33281"
    }, 
    {
      "city": "Năvodari", 
      "lat": "44.3208", 
      "lng": "28.6125", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Constanţa", 
      "capital": "", 
      "population": "32981", 
      "population_proper": "32981"
    }, 
    {
      "city": "Câmpina", 
      "lat": "45.1281", 
      "lng": "25.7383", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Prahova", 
      "capital": "", 
      "population": "32935", 
      "population_proper": "32935"
    }, 
    {
      "city": "Mioveni", 
      "lat": "44.9553", 
      "lng": "24.9356", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Argeş", 
      "capital": "", 
      "population": "31998", 
      "population_proper": "31998"
    }, 
    {
      "city": "Câmpulung", 
      "lat": "45.2750", 
      "lng": "25.0500", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Argeş", 
      "capital": "", 
      "population": "31767", 
      "population_proper": "31767"
    }, 
    {
      "city": "Caracal", 
      "lat": "44.1000", 
      "lng": "24.3333", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Olt", 
      "capital": "", 
      "population": "30954", 
      "population_proper": "30954"
    }, 
    {
      "city": "Săcele", 
      "lat": "45.6175", 
      "lng": "25.6878", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Braşov", 
      "capital": "", 
      "population": "30798", 
      "population_proper": "30798"
    }, 
    {
      "city": "Făgăraş", 
      "lat": "45.8422", 
      "lng": "24.9714", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Braşov", 
      "capital": "", 
      "population": "30714", 
      "population_proper": "30714"
    }, 
    {
      "city": "Feteşti", 
      "lat": "44.4150", 
      "lng": "27.8236", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Ialomiţa", 
      "capital": "", 
      "population": "30217", 
      "population_proper": "30217"
    }, 
    {
      "city": "Sighişoara", 
      "lat": "46.2169", 
      "lng": "24.7911", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Mureş", 
      "capital": "", 
      "population": "28102", 
      "population_proper": "28102"
    }, 
    {
      "city": "Borşa", 
      "lat": "47.6553", 
      "lng": "24.6631", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Maramureş", 
      "capital": "", 
      "population": "27611", 
      "population_proper": "27611"
    }, 
    {
      "city": "Roşiori de Vede", 
      "lat": "44.0650", 
      "lng": "24.9655", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Teleorman", 
      "capital": "", 
      "population": "27416", 
      "population_proper": "27416"
    }, 
    {
      "city": "Curtea de Argeş", 
      "lat": "45.1167", 
      "lng": "24.6667", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Argeş", 
      "capital": "", 
      "population": "27359", 
      "population_proper": "27359"
    }, 
    {
      "city": "Sebeş", 
      "lat": "45.9547", 
      "lng": "23.5700", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Alba", 
      "capital": "", 
      "population": "27019", 
      "population_proper": "27019"
    }, 
    {
      "city": "Huşi", 
      "lat": "46.6731", 
      "lng": "28.0647", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Vaslui", 
      "capital": "", 
      "population": "26266", 
      "population_proper": "26266"
    }, 
    {
      "city": "Fălticeni", 
      "lat": "47.4625", 
      "lng": "26.3000", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Suceava", 
      "capital": "", 
      "population": "25723", 
      "population_proper": "25723"
    }, 
    {
      "city": "Pantelimon", 
      "lat": "44.4528", 
      "lng": "26.2036", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Ilfov", 
      "capital": "", 
      "population": "25596", 
      "population_proper": "25596"
    }, 
    {
      "city": "Olteniţa", 
      "lat": "44.0864", 
      "lng": "26.6364", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Călăraşi", 
      "capital": "", 
      "population": "24822", 
      "population_proper": "24822"
    }, 
    {
      "city": "Turnu Măgurele", 
      "lat": "43.7517", 
      "lng": "24.8708", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Teleorman", 
      "capital": "", 
      "population": "24772", 
      "population_proper": "24772"
    }, 
    {
      "city": "Caransebeş", 
      "lat": "45.4214", 
      "lng": "22.2219", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Caraş-Severin", 
      "capital": "", 
      "population": "24689", 
      "population_proper": "24689"
    }, 
    {
      "city": "Dorohoi", 
      "lat": "47.9597", 
      "lng": "26.3997", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Botoşani", 
      "capital": "", 
      "population": "24309", 
      "population_proper": "24309"
    }, 
    {
      "city": "Vulcan", 
      "lat": "45.3811", 
      "lng": "23.2914", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "", 
      "population": "24160", 
      "population_proper": "24160"
    }, 
    {
      "city": "Rădăuţi", 
      "lat": "47.8425", 
      "lng": "25.9192", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Suceava", 
      "capital": "", 
      "population": "23822", 
      "population_proper": "23822"
    }, 
    {
      "city": "Zărneşti", 
      "lat": "45.5725", 
      "lng": "25.3431", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Braşov", 
      "capital": "", 
      "population": "23476", 
      "population_proper": "23476"
    }, 
    {
      "city": "Lupeni", 
      "lat": "45.3603", 
      "lng": "23.2383", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "", 
      "population": "23390", 
      "population_proper": "23390"
    }, 
    {
      "city": "Aiud", 
      "lat": "46.3103", 
      "lng": "23.7167", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Alba", 
      "capital": "", 
      "population": "22876", 
      "population_proper": "22876"
    }, 
    {
      "city": "Petrila", 
      "lat": "45.4511", 
      "lng": "23.3981", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Hunedoara", 
      "capital": "", 
      "population": "22692", 
      "population_proper": "22692"
    }, 
    {
      "city": "Câmpia Turzii", 
      "lat": "46.5444", 
      "lng": "23.8792", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Cluj", 
      "capital": "", 
      "population": "22223", 
      "population_proper": "22223"
    }, 
    {
      "city": "Buftea", 
      "lat": "44.5700", 
      "lng": "25.9500", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Ilfov", 
      "capital": "", 
      "population": "22178", 
      "population_proper": "22178"
    }, 
    {
      "city": "Târnăveni", 
      "lat": "46.3297", 
      "lng": "24.2700", 
      "country": "Romania", 
      "iso2": "RO", 
      "admin_name": "Mureş", 
      "capital": "", 
      "population": "22075", 
      "population_proper": "22075"
    }, 
]